packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': false
  '@prisma/client': false
  '@scarf/scarf': true
  '@swc/core': false
  better-sqlite3: false
  esbuild: true
  msgpackr-extract: false
  unrs-resolver: true
